version: '3.8'

services:
  grocery-list:
    build:
      context: .
      dockerfile: grocery-list2/Dockerfile
      platforms:
        - linux/amd64
    image: boldo42/grocery-list-vite
    ports:
      - "8000:8000"  # Adjust port as needed
    env_file:
      - grocery-list2/.env  # Path to your .env file
    volumes:
      - ./grocery-list2:/app  # Optional: for development hot-reload
    restart: unless-stopped