# ============================================================================
# Lookup table for item name denoising
# ============================================================================

FILLER_WORDS = {
    # ====================
    # ENGLISH
    # ====================
    # marketing / quality
    "the": "",
    "premium": "",
    "superior": "",
    "finest": "",
    "best": "",
    "selected": "",
    "carefully selected": "",
    "special": "",
    "exclusive": "",
    "authentic": "",
    "traditional": "",
    "classic": "",
    "original": "",
    "signature": "",
    "artisan": "",
    "artisanal": "",
    "handcrafted": "",
    "homemade": "",
    "homestyle": "",
    "gourmet": "",
    "deluxe": "",
    # texture / experience
    "crispy": "",
    "crunchy": "",
    "smooth": "",
    "creamy": "",
    "soft": "",
    "tender": "",
    "juicy": "",
    "rich": "",
    # preparation / processing
    "ready to eat": "",
    "ready-to-eat": "",
    "easy to prepare": "",
    "quick cook": "",
    "instant": "",
    "microwaveable": "",
    "oven ready": "",
    "pre cooked": "",
    "pre-cooked": "",
    "slow cooked": "",
    "stone baked": "",
    # dietary / claims
    "organic": "",
    "bio": "",
    "natural": "",
    "no additives": "",
    "no preservatives": "",
    "no artificial colors": "",
    "no artificial flavours": "",
    "non gmo": "",
    "gmo free": "",
    "gluten free": "",
    "gluten-free": "",
    "lactose free": "",
    "lactose-free": "",
    "vegan": "",
    "vegetarian": "",
    "plant based": "",
    "plant-based": "",
    "low fat": "",
    "reduced fat": "",
    "low sugar": "",
    "sugar free": "",
    "sugar-free": "",
    "high protein": "",
    "protein rich": "",
    # vague flavor phrasing
    "stark": "",
    "extra": "",
    "ohne": "",
    "flavoured": "",
    "flavored": "",
    "with flavor": "",
    "taste of": "",
    "hint of": "",
    "touch of": "",
    "style": "",
    # convenience / pack
    "family pack": "",
    "value pack": "",
    "multipack": "",
    "portion": "",
    "single serve": "",
    "snack size": "",
    "beste": "",
    "feinste": "",
    "ausgewählt": "",
    "besondere": "",
    "exklusiv": "",
    "authentisch": "",
    "traditionell": "",
    "klassisch": "",
    "hausgemacht": "",
    "handgemacht": "",
    "manufaktur": "",
    "delikat": "",
    # texture / experience
    "knusprig": "",
    "kross": "",
    "cremig": "",
    "zart": "",
    "saftig": "",
    "reichhaltig": "",
    # preparation / processing
    "verzehrfertig": "",
    "schnell zubereitet": "",
    "fix und fertig": "",
    "mikrowellengeeignet": "",
    "ofenfertig": "",
    "vorgegart": "",
    "langsam gegart": "",
    "steinofen": "",
    # dietary / claims
    "natürlich": "",
    "ohne zusatzstoffe": "",
    "ohne konservierungsstoffe": "",
    "ohne farbstoffe": "",
    "ohne geschmacksverstärker": "",
    "gentechnikfrei": "",
    "glutenfrei": "",
    "laktosefrei": "",
    "vegetarisch": "",
    "pflanzlich": "",
    "fettarm": "",
    "fettreduziert": "",
    "zuckerarm": "",
    "zuckerfrei": "",
    "eiweißreich": "",
    # vague flavor phrasing
    "aromatisiert": "",
    "geschmack": "",
    "geschmack von": "",
    "nach art": "",
    "art": "",
    "husten": "",
    # convenience / pack
    "familienpackung": "",
    "vorteilspack": "",
    "mehrpack": "",
    "portioniert": "",
    "einzelportion": "",
    "snackgröße": "",
    # ====================
    # FRENCH
    # ====================
    "qualité supérieure": "",
    "traditionnel": "",
    "classique": "",
    "authentique": "",
    "fait maison": "",
    "croustillant": "",
    "crémeux": "",
    "prêt à consommer": "",
    "naturel": "",
    "sans additifs": "",
    "sans conservateurs": "",
    "sans gluten": "",
    "sans lactose": "",
    "végan": "",
    "végétarien": "",
    "aromatisé": "",
    "saveur": "",
    "au goût de": "",
    "format familial": "",
    # ====================
    # SPANISH
    # ====================
    "calidad superior": "",
    "tradicional": "",
    "clásico": "",
    "auténtico": "",
    "casero": "",
    "crujiente": "",
    "cremoso": "",
    "listo para comer": "",
    "sin aditivos": "",
    "sin conservantes": "",
    "sin gluten": "",
    "sin lactosa": "",
    "vegano": "",
    "vegetariano": "",
    "aromatizado": "",
    "sabor": "",
    "al gusto de": "",
    "formato familiar": "",
}

FOOD_BRAND_MAP = {
    # Germany
    "weihenstephan": "",
    "müller": "",
    "mueller": "",
    "ehrmann": "",
    "dr. oetker": "",
    "rügenwalder mühle": "",
    "ruegenwalder muehle": "",
    "alnatura": "",
    "alpro": "",
    "henglein": "",
    "knorr": "",
    "maggi": "",
    "milka": "",
    "haribo": "",
    "hipp": "",
    "iglo": "",
    "kühne": "",
    "kuehne": "",
    "thomy": "",
    "zott": "",
    "berchtesgadener land": "",
    "meggle": "",
    "kerrygold": "",
    "dallmayr": "",
    "tchibo": "",
    # UK
    "tesco": "",
    "sainsbury's": "",
    "sainsburys": "",
    "waitrose": "",
    "marks & spencer": "",
    "marks and spencer": "",
    "morrisons": "",
    "asda": "",
    "heinz": "",
    "cadbury": "",
    "walkers": "",
    "warburtons": "",
    "birds eye": "",
    "mcvitie's": "",
    "mcvities": "",
    "branston": "",
    "bisto": "",
    "pg tips": "",
    "twinings": "",
    # Spain
    "hacendado": "",
    "gallina blanca": "",
    "gallo": "",
    "carbonell": "",
    "campofrío": "",
    "campofrio": "",
    "elpozo": "",
    "central lechera asturiana": "",
    "kaiku": "",
    "pascual": "",
    "bimbo": "",
    "don simón": "",
    "don simon": "",
    "la española": "",
    "la espanola": "",
    "hero": "",
    "cuétara": "",
    "cuetara": "",
    # France
    "danone": "",
    "président": "",
    "president": "",
    "lactel": "",
    "yoplait": "",
    "bonne maman": "",
    "fleury michon": "",
    "herta": "",
    "panzani": "",
    "amora": "",
    "maille": "",
    "andros": "",
    "elle & vire": "",
    "elle and vire": "",
    "casino": "",
    "carrefour": "",
    "auchan": "",
    # USA
    "kraft": "",
    "kraft heinz": "",
    "general mills": "",
    "kellogg's": "",
    "kelloggs": "",
    "nestlé": "",
    "nestle": "",
    "campbell's": "",
    "campbells": "",
    "hormel": "",
    "tyson": "",
    "perdue": "",
    "dole": "",
    "del monte": "",
    "chobani": "",
    "philadelphia": "",
    "oscar mayer": "",
    "planters": "",
    "jif": "",
    "skippy": "",
    "smucker's": "",
    "smuckers": "",
    "land o'lakes": "",
    "land olakes": "",
    "blue diamond": "",
    "hidden valley": "",
    "stouffer's": "",
    "stouffers": "",
    # Store brands (important!)
    "edeka": "",
    "rewe": "",
    "gut & günstig": "",
    "gut und günstig": "",
    "ja!": "",
    "k-classic": "",
    "lidl": "",
    "aldi": "",
    "aldi süd": "",
    "aldi sud": "",
    "aldi nord": "",
    "mercadona": "",
}


TYPO_CORRECTIONS = {
    "mayonesse": "mayonnaise",
    "chapaty": "chapati",
    "kokusnuss": "kokosnuss",
    "doppelrahmstufe": "frischkäse",
    "salatmayo": "mayonnaise",
    "vegane salatmayo": "mayonnaise",
    "indian chicken tikka": "chicken tikka",
}


CANONICAL_COMPOUNDS = {
    "hafer milch": "hafermilch",
    "reis essig": "reisessig",
}


WORD_STRIP = FILLER_WORDS
WORD_STRIP.update(FOOD_BRAND_MAP)
WORD_STRIP.update(TYPO_CORRECTIONS)
WORD_STRIP["sojaprodukt"] = "sojajoghurt"


PHRASE_STRIP = [
    "ready to eat",
    "ready-to-eat",
    "gluten free",
    "gluten-free",
    "lactose free",
    "lactose-free",
    "sans gluten",
    "sans lactose",
    "sin gluten",
    "sin lactosa",
    "au goût de",
    "nach art",
    "ungarische art",
    "format familial",
    "family pack",
    "value pack",
    "gepufft mit",
    "gesüßt",
    "gesusst",
    "fermentiertes sojaprodukt",
    "sommerblüte",
    "sommerbluete",
]
