# ============================================================================
# Lookup table for item name denoising
# ============================================================================
WORD_STRIP = {
    # ====================
    # ENGLISH
    # ====================
    # marketing / quality
    "the": "",
    "premium": "",
    "superior": "",
    "finest": "",
    "best": "",
    "selected": "",
    "carefully selected": "",
    "special": "",
    "exclusive": "",
    "authentic": "",
    "traditional": "",
    "classic": "",
    "original": "",
    "signature": "",
    "artisan": "",
    "artisanal": "",
    "handcrafted": "",
    "homemade": "",
    "homestyle": "",
    "gourmet": "",
    "deluxe": "",
    # texture / experience
    "crispy": "",
    "crunchy": "",
    "smooth": "",
    "creamy": "",
    "soft": "",
    "tender": "",
    "juicy": "",
    "rich": "",
    # preparation / processing
    "ready to eat": "",
    "ready-to-eat": "",
    "easy to prepare": "",
    "quick cook": "",
    "instant": "",
    "microwaveable": "",
    "oven ready": "",
    "pre cooked": "",
    "pre-cooked": "",
    "slow cooked": "",
    "stone baked": "",
    # dietary / claims
    "organic": "",
    "bio": "",
    "natural": "",
    "no additives": "",
    "no preservatives": "",
    "no artificial colors": "",
    "no artificial flavours": "",
    "non gmo": "",
    "gmo free": "",
    "gluten free": "",
    "gluten-free": "",
    "lactose free": "",
    "lactose-free": "",
    "vegan": "",
    "vegetarian": "",
    "plant based": "",
    "plant-based": "",
    "low fat": "",
    "reduced fat": "",
    "low sugar": "",
    "sugar free": "",
    "sugar-free": "",
    "high protein": "",
    "protein rich": "",
    # vague flavor phrasing
    "stark": "",
    "extra": "",
    "ohne": "",
    "flavoured": "",
    "flavored": "",
    "with flavor": "",
    "taste of": "",
    "hint of": "",
    "touch of": "",
    "style": "",
    # convenience / pack
    "family pack": "",
    "value pack": "",
    "multipack": "",
    "portion": "",
    "single serve": "",
    "snack size": "",
    "beste": "",
    "feinste": "",
    "ausgewählt": "",
    "besondere": "",
    "exklusiv": "",
    "authentisch": "",
    "traditionell": "",
    "klassisch": "",
    "hausgemacht": "",
    "handgemacht": "",
    "manufaktur": "",
    "delikat": "",
    # texture / experience
    "knusprig": "",
    "kross": "",
    "cremig": "",
    "zart": "",
    "saftig": "",
    "reichhaltig": "",
    # preparation / processing
    "verzehrfertig": "",
    "schnell zubereitet": "",
    "fix und fertig": "",
    "mikrowellengeeignet": "",
    "ofenfertig": "",
    "vorgegart": "",
    "langsam gegart": "",
    "steinofen": "",
    # dietary / claims
    "natürlich": "",
    "ohne zusatzstoffe": "",
    "ohne konservierungsstoffe": "",
    "ohne farbstoffe": "",
    "ohne geschmacksverstärker": "",
    "gentechnikfrei": "",
    "glutenfrei": "",
    "laktosefrei": "",
    "vegetarisch": "",
    "pflanzlich": "",
    "fettarm": "",
    "fettreduziert": "",
    "zuckerarm": "",
    "zuckerfrei": "",
    "eiweißreich": "",
    # vague flavor phrasing
    "aromatisiert": "",
    "geschmack": "",
    "geschmack von": "",
    "nach art": "",
    "art": "",
    "husten": "",
    # convenience / pack
    "familienpackung": "",
    "vorteilspack": "",
    "mehrpack": "",
    "portioniert": "",
    "einzelportion": "",
    "snackgröße": "",
    # ====================
    # FRENCH
    # ====================
    "qualité supérieure": "",
    "traditionnel": "",
    "classique": "",
    "authentique": "",
    "fait maison": "",
    "croustillant": "",
    "crémeux": "",
    "prêt à consommer": "",
    "naturel": "",
    "sans additifs": "",
    "sans conservateurs": "",
    "sans gluten": "",
    "sans lactose": "",
    "végan": "",
    "végétarien": "",
    "aromatisé": "",
    "saveur": "",
    "au goût de": "",
    "format familial": "",
    # ====================
    # SPANISH
    # ====================
    "calidad superior": "",
    "tradicional": "",
    "clásico": "",
    "auténtico": "",
    "casero": "",
    "crujiente": "",
    "cremoso": "",
    "listo para comer": "",
    "sin aditivos": "",
    "sin conservantes": "",
    "sin gluten": "",
    "sin lactosa": "",
    "vegano": "",
    "vegetariano": "",
    "aromatizado": "",
    "sabor": "",
    "al gusto de": "",
    "formato familiar": "",
}

PHRASE_STRIP = [
    "ready to eat",
    "ready-to-eat",
    "gluten free",
    "gluten-free",
    "lactose free",
    "lactose-free",
    "sans gluten",
    "sans lactose",
    "sin gluten",
    "sin lactosa",
    "au goût de",
    "nach art",
    "ungarische art",
    "format familial",
    "family pack",
    "value pack",
]
